### ISSUE TITLE
[Q] How does '-cpu' work?

### ISSUE THREAD

**Issue by RainbowMiner** [TrailingStop/TT-Miner-release#49]
Most CPU miners give us two parameters, like '--threads/-t' and '--affinity', so that we can define exactly, which cores and/or threads should be used for mining. Since TTminer comes with '-cpu <threads>' only: how does this parameter work exactly? 
How does it distribute the mining load over all available cores/threads?

Example a AMD Ryzen5 with 8 cores / 16 threads. What will happen if we set '-cpu 14' ?

On classic CpuminerOpt, we would set '-t 14 --affinity 0xFFF5', that would use all cores plus 6 of the threads.

**Comment by TrailingStop** [comment]
TT checks the cpu/thread/core/cache topology. It is focused to make best used of the available cache. here are the two most important rules TT uses to select 'threads'.
- always make sure to use the same number of threads per available l3 cache.
- select threads so, that they do not need to share l2

You can see how it works if you run TT with -t 1, then -t 2 and continue to add threads. you will see how it distribute the threads to the l3 blocks and how it picks the cores that do not need to share l2

**Comment by TrailingStop** [comment]
Hi.-Cpu created a open l device from the CPU. Am 15.07.2024 12:45 schrieb RainbowMiner ***@***.***>:
Most CPU miners give us two parameters, like '--threads/-t' and '--affinity', so that we can define exactly, which cores and/or threads should be used for mining. Since TTminer comes with '-cpu ' only: how does this parameter work exactly?
How does it distribute the mining load over all available cores/threads?
Example a AMD Ryzen5 with 8 cores / 16 threads. What will happen if we set '-cpu 14' ?
